#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd `dirname ${DIR}`

./script/build

VERSION=`cat VERSION`

IMAGE="quay.io/bakins/php-fpm-exporter:${VERSION}"

docker build -t ${IMAGE} .
docker push ${IMAGE}
