#!/usr/bin/env bash
set -eu
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd `dirname ${DIR}`

docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

IMAGE="bakins/php-fpm-exporter:${$TRAVIS_TAG}"

docker build -t ${IMAGE} .

docker push ${IMAGE}

