#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd `dirname ${DIR}`

./script/build

VERSION=`cat VERSION`

IMAGE="bakins/php-fpm-exporter:${VERSION}"

docker build -t ${IMAGE} .

docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

docker push ${IMAGE}
